In [22]:
import numpy as np
from io import StringIO
import pandas as pd

# The names argument

In [11]:
data = StringIO("1 2 3\n 4 5 6")
np.genfromtxt(data, dtype=[(_,int) for _ in "abc"])

array([(1, 2, 3), (4, 5, 6)],
      dtype=[('a', '<i4'), ('b', '<i4'), ('c', '<i4')])

In [20]:
data = StringIO("1 2 3\n4 5 6")
_ = np.genfromtxt(data, names="A, B, C")
_

array([(1., 2., 3.), (4., 5., 6.)],
      dtype=[('A', '<f8'), ('B', '<f8'), ('C', '<f8')])

In [23]:
pd.DataFrame(_)

A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0

In [24]:
data = StringIO("So it goes\n#a b c \n1 2 3\n 4 5 6")
_  = np.genfromtxt(data, skip_header=1, names=True)
_

array([(1., 2., 3.), (4., 5., 6.)],
      dtype=[('a', '<f8'), ('b', '<f8'), ('c', '<f8')])

In [25]:
pd.DataFrame(_)

a    b    c
0  1.0  2.0  3.0
1  4.0  5.0  6.0

In [31]:
data = StringIO("1 2 3\n3 4 5 ")
ndtype = [("a",int),("b", float),("c", int)]
names = ["A", "B", "C"]

_ = np.genfromtxt(data, names = names, dtype = ndtype)
_

array([(1, 2., 3), (3, 4., 5)],
      dtype=[('A', '<i4'), ('B', '<f8'), ('C', '<i4')])

In [32]:
pd.DataFrame(_)

A    B  C
0  1  2.0  3
1  3  4.0  5

## The defaultfmt argument

In [41]:
# The names=None but a structured dtype is expected,names are defined with the standard Numpy default of "f%i",
# yielding names like f0, f1 and so forth
data = StringIO("1 2 3\n4 5 6")
_ = np.genfromtxt(data,names="a", dtype = (int, float, int))
_

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('a', '<i4'), ('f0', '<f8'), ('f1', '<i4')])

## Validating names

## Tweaking the conversion

In [46]:
convertfunc = lambda x : float(x.strip(b"%"))/100
convertfunc(" 10")

TypeError: strip arg must be None or str

## Indexing in Numpy

## Assignment Vs Referencing

In [47]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
x.shape = (2,5)

In [53]:
x[1,3]

8

## Other Indexing options

In [54]:
x = np.arange(10)

In [55]:
x[2:5]

array([2, 3, 4])

In [57]:
x[:-5]

array([0, 1, 2, 3, 4])

In [58]:
y = np.arange(35).reshape(5,-1)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [61]:
y[1:5:2,::3] #.copy() is recommended if the original data is not required anymore

array([[ 7, 10, 13],
       [21, 24, 27]])