In [1]:
# https://numpy.org/devdocs/user/absolute_beginners.html

In [2]:
import numpy as np

In [8]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.arange(6).reshape(-1,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
np.arange(2,9,2)

array([2, 4, 6, 8])