In [1]:
# https://numpy.org/devdocs/user/absolute_beginners.html

In [2]:
import numpy as np

In [8]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.arange(6).reshape(-1,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [23]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [24]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [33]:
import pandas as pd
numpy_ = pd.DataFrame({"NUMPY":list(dir(np)) })
panda_ = pd.DataFrame({ "Pandas" :list(dir(pd))})

In [39]:
x = np.ones(10, dtype=np.int64).reshape(2,5)
x

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

## Adding, Removing and sorting Elements

In [40]:
arr = np.array([2,1,5,3,7,4,6,8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [42]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6]])

In [46]:
x

array([[1, 2],
       [3, 4]])

In [47]:
y

array([[5, 6]])

In [53]:
np.concatenate([x,y], axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [56]:
x.ndim, y.ndim

(2, 2)

### Shape and size of the array

In [57]:
a  = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [58]:
a.reshape([-1])

array([1, 2, 3, 4, 5, 6])

In [60]:
b = np.expand_dims(a,axis=0)

In [62]:
b.shape

(1, 6)